import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "@/utils/api";
import Image from "next/image";
import logo from '../../public/logo-ico.svg'

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center text-white bg-black">
        <Image src={'/logo-ico.svg'} alt="logo" width="500" height="500"  />
      </main>
    </>
  );
};

export default Home;
